import Database from "better-sqlite3";
import { writeFileSync } from "fs";

// Pull every DC charging session out of the decoded archive into one compact fixture, so the
// check can replay them in CI with no database present. Scratch tooling: it reads the evidence
// DBs read-only and writes a .ts fixture; it is not part of the app.

const DBS = process.argv.slice(2, -1);
const OUT = process.argv[process.argv.length - 1];
/**
 * DC charging when the pack is taking more than this.
 *
 * ⚠️ 25 A, not 5: delimited on `pack_a` because `fast_dc_target_a` gaps hide whole sessions, but
 * the bike's AC charger tops out around 8-10 A at the pack, so a 5 A threshold pulls in every AC
 * charge and every long park. Nothing in the archive charges DC below 19.5 A (the derate), so 25
 * separates the two cleanly.
 */
const CHARGING_A = 25;
const GAP_MS = 10 * 60_000;
const MIN_MINUTES = 4;
/** The archive holds rows dated past 2027 from a Pi with no RTC. */
const TS_MIN = Date.parse("2026-08-01T00:00:00Z");
const TS_MAX = Date.parse("2026-09-19T00:00:00Z");

interface Row {
  ts: number;
  value: number;
}
interface Session {
  name: string;
  fromMs: number;
  toMs: number;
  temperature: Row[];
  packA: Row[];
  requested: Row[];
  coolantIn: Row[];
  soc: Row[];
  ceiling: Row[];
}

/**
 * At most one row per `everyMs`, plus the last.
 *
 * ⚠️ Time only, never "and when the value changed": `coolant_in` has a 0.05 K deadband and changes
 * on nearly every sample, so a value-aware thinner kept 4 256 rows of one session and made the
 * fixture a megabyte. These are slow signals and the plant integrates them.
 */
function thin(rows: Row[], everyMs: number): Row[] {
  const kept: Row[] = [];
  for (const row of rows) {
    const last = kept.at(-1);
    if (last === undefined || row.ts - last.ts >= everyMs) kept.push(row);
  }
  const final = rows.at(-1);
  if (final !== undefined && kept.at(-1) !== final) kept.push(final);
  return kept;
}

/** `"<ms>:<value> …"`, times relative to the session start, values to `places` decimals. */
function pack(rows: Row[], fromMs: number, places: number): string {
  return rows.map(row => `${row.ts - fromMs}:${row.value.toFixed(places)}`).join(" ");
}

const sessions: Session[] = [];
for (const path of DBS) {
  const db = new Database(path, { readonly: true });
  const ids = new Map(
    (db.prepare("select id, key from signal").all() as { id: number; key: string }[]).map(r => [r.key, r.id])
  );
  const read = (key: string, from = TS_MIN, to = TS_MAX): Row[] => {
    const id = ids.get(key);
    if (id === undefined) return [];
    return db
      .prepare("select distinct ts, value from reading where signal_id = ? and ts between ? and ? order by ts")
      .all(id, from, to) as Row[];
  };
  const packA = read("pack_a");
  const label = path.replace(/^.*\//, "").replace(/\.db$/, "");
  // Split the charging rows on gaps.
  let start: number | null = null,
    last = 0;
  const spans: { from: number; to: number }[] = [];
  for (const row of packA) {
    if (row.value <= CHARGING_A) continue;
    if (start === null || row.ts - last > GAP_MS) {
      if (start !== null && last - start >= MIN_MINUTES * 60_000) spans.push({ from: start, to: last });
      start = row.ts;
    }
    last = row.ts;
  }
  if (start !== null && last - start >= MIN_MINUTES * 60_000) spans.push({ from: start, to: last });
  for (const span of spans) {
    const temperature = read("batt_temp_hi", span.from - 600_000, span.to);
    if (temperature.length < 3) continue;
    // A DC session is one the vehicle asked the station for. Without a request row this is a fast
    // AC charge or a decode gap, and it cannot be replayed against a rule that commands a ceiling.
    const requested = read("fast_dc_target_a", span.from, span.to);
    if (requested.length === 0) continue;
    sessions.push({
      name: `${label}@${new Date(span.from).toISOString().slice(5, 16).replace("T", " ")}`,
      fromMs: span.from,
      toMs: span.to,
      temperature,
      packA: [],
      requested: thin(requested, 15_000),
      coolantIn: thin(read("coolant_in", span.from - 600_000, span.to), 120_000),
      soc: read("soc", span.from, span.to),
      ceiling: read("fast_dc_limit_max_a", span.from - 3_600_000, span.to),
    });
  }
  db.close();
}
sessions.sort((a, b) => a.fromMs - b.fromMs);
console.log(`${sessions.length} sessions`);
for (const s of sessions) {
  const minutes = (s.toMs - s.fromMs) / 60_000;
  const temps = s.temperature.map(r => r.value);
  console.log(
    `  ${s.name}  ${minutes.toFixed(0).padStart(3)} min  temps ${Math.min(...temps)}-${Math.max(...temps)} (${s.temperature.length} rows)  coolant ${s.coolantIn.length}  soc ${s.soc.length}  ceiling ${s.ceiling.at(-1)?.value ?? "—"}`
  );
}
const header = `// GENERATED by evidence/extract-archive-sessions.ts from the decoded archive — DO NOT EDIT.
//
// Every DC charging session on record: 2026-09-07 to 2026-09-18, delimited on \`pack_a\` > 25 A with
// gaps over ten minutes, each one carrying the rings the controller would have seen. The decoded
// databases are gitignored evidence in another worktree and CI has none of them, so the data is
// baked here the way scripts/charge-auto-episode.ts bakes its three episodes — this is the same
// idea over the whole archive rather than three hand-picked stops.
//
// ⚠️ Thinned, and only where thinning cannot change a decision: \`batt_temp_hi\` and \`soc\` are
// whole-number log-on-change signals and are kept ENTIRE; \`coolant_in\` (a 0.05 K deadband, ~6
// rows/min) keeps one row per value change or two minutes, whichever comes first, and
// \`fast_dc_target_a\` one per change or fifteen seconds. \`pack_a\` is dropped: the replay computes
// the current itself.

/**
 * One signal as \`"<ms>:<value> <ms>:<value> …"\`, ms from the session's first charging sample.
 *
 * ⚠️ A STRING, and it is not obfuscation: as an array of objects — or even of tuples — prettier
 * prints one row per line and eighteen sessions of real signal become a 4 000-line file nobody
 * can review. One line per signal keeps the diff readable and the data intact;
 * scripts/charge-auto-archive.ts parses it into the rule's own sample types once, on load.
 */
export type ArchiveSignal = string;

export interface ArchiveSession {
  /** Which decoded database and when, in CEST — the name used in every assertion message. */
  name: string;
  /** How long the pack drew more than 25 A, in ms. */
  spanMs: number;
  /** \`batt_temp_hi\`, whole degrees, entire. The ring the estimator sees. */
  temperature: ArchiveSignal;
  /** \`soc\`, whole percent, entire. */
  soc: ArchiveSignal;
  /** \`fast_dc_target_a\` — what the vehicle asked the station for. */
  requested: ArchiveSignal;
  /** \`coolant_in\`, the loop's cold end, for the closed-loop plant. */
  coolantIn: ArchiveSignal;
  /** \`fast_dc_limit_max_a\` as last seen before or during the session. */
  ceilingAmps: number;
}

export const ARCHIVE_SESSIONS: ArchiveSession[] = `;
const asFixture = sessions.map(s => ({
  name: s.name,
  spanMs: s.toMs - s.fromMs,
  temperature: pack(s.temperature, s.fromMs, 0),
  soc: pack(s.soc, s.fromMs, 0),
  requested: pack(s.requested, s.fromMs, 0),
  coolantIn: pack(s.coolantIn, s.fromMs, 2),
  ceilingAmps: s.ceiling.at(-1)?.value ?? 75,
}));
writeFileSync(OUT, header + JSON.stringify(asFixture, null, 0) + ";\n");
console.log(`wrote ${OUT}`);
